name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: 
  batch: false
  branches: 
    include:
      - main
  paths:
    include:
      - "*"

variables:
  agentImage: windows-2019

  # arm deployment
  azureSubscription: RossHopkinsIC
  resourceGroupName: RG-ADO-LogStreamer
  location: westus2
  armTemplate: drop/armTemplates/deploy.json

  # function app
  functionAppName: adoLogStreamer
  azureDevOpsOrg: Hoppy7
  azureDevOpsProject: Azure
  adoPatKeyvaultSecretUri: https://kv-rohopkin.vault.azure.net/secrets/adoLogStreamerPat/

  # storage account
  storageAccountName: adologstreamerstg1
  storageAccountContainer: pipelinerunlogs
  storageAccountQueue: pipelineruns

stages:
- stage: Build
  jobs:
  - job: Build
    workspace:
      clean: all
    pool:
      vmImage: windows-2019
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)
        includeRootFolder: false 
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)\adoLogStreamer.zip
        replaceExistingArchive: true

    - task: CopyFiles@2
      condition: succeeded()
      displayName: Copy Files to ArtifactStagingDirectory
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        contents: '**'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      condition: succeeded()
      displayName: 'Publish Artifact'

- template: templates/functionApp-release.yml
  parameters:
    environmentName: FunctionAppRelease
    agentImage: $(agentImage)
    azureSubscription: $(azureSubscription)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    armTemplate: $(armTemplate)
    functionAppName: $(functionAppName)
    azureDevOpsOrg: $(azureDevOpsOrg)
    azureDevOpsProject: $(azureDevOpsProject)
    adoPatKeyvaultSecretUri: $(adoPatKeyvaultSecretUri)
    storageAccountName: $(storageAccountName)
    storageAccountContainer: $(storageAccountContainer)
    storageAccountQueue: $(storageAccountQueue)
    deploymentMode: Complete

- template: templates/streamLogs.yml
  parameters:
    azureSubscription: $(azureSubscription)
    storageAccountName: $(storageAccountName)
    storageAccountRG: $(resourceGroupName)
    storageAccountQueue: $(storageAccountQueue)